# Generated by Django 5.2.11 on 2026-02-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('fitness_goal', models.CharField(choices=[('cutting', 'Cutting'), ('bulking', 'Bulking'), ('maintenance', 'Maintenance')], default='maintenance', max_length=20)),
                ('dietary_preferences', models.JSONField(blank=True, default=list, help_text='List of dietary tags, e.g. ["vegan", "halal"]')),
                ('current_body_type', models.CharField(blank=True, choices=[('ectomorph', 'Ectomorph'), ('mesomorph', 'Mesomorph'), ('endomorph', 'Endomorph')], default='', max_length=20)),
                ('goal_body_type', models.CharField(blank=True, choices=[('ectomorph', 'Ectomorph'), ('mesomorph', 'Mesomorph'), ('endomorph', 'Endomorph')], default='', max_length=20)),
                ('knowledge_rank', models.IntegerField(default=0)),
                ('calorie_target', models.IntegerField(default=2000)),
                ('protein_target', models.IntegerField(default=150, help_text='Grams per day')),
                ('carbs_target', models.IntegerField(default=200, help_text='Grams per day')),
                ('fat_target', models.IntegerField(default=65, help_text='Grams per day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
