# Generated by Django 5.2.11 on 2026-03-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Height in inches', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recommended_daily_calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recommended_weekly_workouts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timeline',
            field=models.CharField(blank=True, choices=[('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('1_year', '1 Year'), ('2_plus_years', '2+ Years')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Weight in lbs', max_digits=5, null=True),
        ),
    ]
