# Generated by Django 5.2.11 on 2026-02-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')])),
                ('category', models.CharField(help_text='E.g. "Nutrition", "Training", "Recovery"', max_length=50)),
                ('front_text', models.TextField(help_text='The question or fact shown first')),
                ('back_text', models.TextField(help_text='The detailed explanation revealed on flip')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField(help_text='Ordered list of four answer strings, e.g. ["A", "B", "C", "D"]')),
                ('correct_answer_index', models.IntegerField(help_text='Zero-based index into ``options`` for the correct answer')),
                ('explanation', models.TextField(blank=True, default='', help_text='Shown to the user after quiz completion')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('score', models.IntegerField(help_text='Number of correct answers')),
                ('total_questions', models.IntegerField()),
                ('assigned_rank', models.IntegerField(help_text='1=Beginner, 2=Intermediate, 3=Advanced')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
    ]
