# Generated by Django 5.2.11 on 2026-02-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('food_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('calories', models.IntegerField(default=0)),
                ('protein_g', models.FloatField(default=0)),
                ('carbs_g', models.FloatField(default=0)),
                ('fat_g', models.FloatField(default=0)),
                ('fiber_g', models.FloatField(default=0)),
                ('serving_size', models.CharField(blank=True, default='', max_length=100)),
                ('nutritional_details', models.JSONField(blank=True, default=dict, help_text='Micronutrients: sodium_mg, sugar_g, vitamin_a_pct, etc.')),
                ('image_url', models.URLField(blank=True, default='', help_text='Public URL of the uploaded food photo in Supabase Storage', max_length=500)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
