# Generated by Django 5.2.11 on 2026-02-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('plan_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10)),
                ('fitness_goal', models.CharField(blank=True, default='', max_length=20)),
                ('dietary_preferences', models.JSONField(blank=True, default=list)),
                ('calorie_target', models.IntegerField(default=2000)),
                ('protein_target', models.IntegerField(default=150)),
                ('carbs_target', models.IntegerField(default=200)),
                ('fat_target', models.IntegerField(default=65)),
                ('favorite_foods', models.TextField(blank=True, default='')),
                ('plan_data', models.JSONField(default=dict, help_text='Structured meal plan with days, meals, portions, and macros')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
