# Generated by Django 5.2.11 on 2026-02-17 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('recommended_angle', models.CharField(help_text='E.g. "Side view", "Front view"', max_length=100)),
                ('instructions', models.TextField(blank=True, default='', help_text='Setup and form tips shown to the user before recording')),
                ('metrics_config', models.JSONField(default=dict, help_text='Keypoints used, threshold values, and metric names')),
            ],
        ),
        migrations.CreateModel(
            name='FormAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('video_url', models.URLField(blank=True, default='', help_text='Public URL of the uploaded video in Supabase Storage', max_length=500)),
                ('total_reps', models.IntegerField(default=0)),
                ('good_reps', models.IntegerField(default=0)),
                ('bad_reps', models.IntegerField(default=0)),
                ('rep_details', models.JSONField(default=list, help_text='Per-rep metrics and feedback')),
                ('load_suggestion', models.TextField(blank=True, default='', help_text='AI-generated suggestion for load adjustment based on form quality')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_analysis.exercise')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
